# Generated by Django 4.1.7 on 2023-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_price_itemname_alter_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='itemname',
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='itemname',
            field=models.ManyToManyField(to='myapp.checkboxitem'),
        ),
    ]
