# Generated by Django 4.1.7 on 2023-03-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_checkboxitem_remove_price_itemname_alter_price_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='additems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='itemname',
        ),
        migrations.DeleteModel(
            name='CheckboxItem',
        ),
    ]
